services:
  - type: web
    name: capturevision-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.19.0
    healthCheckPath: /api/health
    autoDeploy: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Accept,Authorization
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
