services:
  - type: web
    name: wedding-planner
    env: node
    buildCommand: npm install && npm run build && npm run build:server
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://wedding-planner-app-qlvw.onrender.com
      - key: NODE_VERSION
        value: 18.19.0
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://capturevision-app.onrender.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Accept,Authorization
