services:
  - type: web
    name: wedding-planner
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /
