services:
  - type: web
    name: capturevision-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://capturevision-app.onrender.com
      - key: CORS_ORIGINS
        value: http://localhost:5173,http://localhost:3000,https://capturevision-app.onrender.com
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Accept,Authorization
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
